"""add is_like

Revision ID: c381ea020c8d
Revises: a8234b07845e
Create Date: 2026-09-16 09:47:03.269394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c381ea020c8d'
down_revision: Union[str, Sequence[str], None] = 'a8234b07845e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('is_like', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'is_like')
    # ### end Alembic commands ###
